from tkinter import *
def click(event):
    global brics
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if brics.get().isdigit():
            value = int(brics.get())
        else:
            value = eval(screen.get())
        brics.set(value)
        screen.update() 
    elif text == "C":
        brics.set("")
        screen.update()
    else:
        brics.set(brics.get() + text)
        screen.update()

root = Tk()
root.title("CALCULATOR")
root.geometry("390x470")
brics = StringVar()
brics.set("")
screen = Entry(root,textvariable = brics,font="Times 24 bold")
screen.pack(fill=X,pady=10)
fr = Frame(root,bg="white",borderwidth=6)
fr.pack(side=LEFT,anchor="nw")
bequal=Button(fr,fg="black",borderwidth=9,text="=",padx=30,pady=30)
bequal.grid(row=0,column=0,padx=2)
bequal.bind("<Button-1>",click)
bpercentage=Button(fr,fg="black",borderwidth=9,text="%",padx=30,pady=30)
bpercentage.grid(row=0,column=1,padx=2)
bpercentage.bind("<Button-1>",click)
bclear=Button(fr,fg="black",borderwidth=9,text="C",padx=30,pady=30)
bclear.grid(row=0,column=2,padx=2)
bclear.bind("<Button-1>",click)
b1=Button(fr,fg="black",borderwidth=9,text="1",padx=30,pady=30)
b1.grid(row=1,column=0,padx=2)
b1.bind("<Button-1>",click)
b2=Button(fr,fg="black",borderwidth=9,text="2",padx=30,pady=30)
b2.grid(row=1,column=1,padx=2)
b2.bind("<Button-1>",click)
b3=Button(fr,fg="black",borderwidth=9,text="3",padx=30,pady=30)
b3.grid(row=1,column=2,padx=2)
b3.bind("<Button-1>",click)
b4=Button(fr,fg="black",borderwidth=9,text="4",padx=30,pady=30)
b4.grid(row=2,column=0,padx=2)
b4.bind("<Button-1>",click)
b5=Button(fr,fg="black",borderwidth=9,text="5",padx=30,pady=30)
b5.grid(row=2,column=1,padx=2)
b5.bind("<Button-1>",click)
b6=Button(fr,fg="black",borderwidth=9,text="6",padx=30,pady=30)
b6.grid(row=2,column=2,padx=2)
b6.bind("<Button-1>",click)
b7=Button(fr,fg="black",borderwidth=9,text="7",padx=30,pady=30)
b7.grid(row=3,column=0,padx=2)
b7.bind("<Button-1>",click)
b8=Button(fr,fg="black",borderwidth=9,text="8",padx=30,pady=30)
b8.grid(row=3,column=1,padx=2)
b8.bind("<Button-1>",click)
b9=Button(fr,fg="black",borderwidth=9,text="9",padx=30,pady=30)
b9.grid(row=3,column=2,padx=2)
b9.bind("<Button-1>",click)
badd=Button(fr,fg="black",borderwidth=9,text="+",padx=30,pady=30)
badd.grid(row=0,column=4,padx=2)
badd.bind("<Button-1>",click)
bsub=Button(fr,fg="black",borderwidth=9,text="-",padx=30,pady=30)
bsub.grid(row=1,column=4,padx=2)
bsub.bind("<Button-1>",click)
bmul=Button(fr,fg="black",borderwidth=9,text="*",padx=30,pady=30)
bmul.grid(row=2,column=4,padx=2)
bmul.bind("<Button-1>",click)
bdiv=Button(fr,fg="black",borderwidth=9,text="/",padx=30,pady=30)
bdiv.grid(row=3,column=4,padx=2)
bdiv.bind("<Button-1>",click)
root.mainloop()